import Sidebar from "@/Components/Shared/Sidebar";

export const metadata = {
  title: "Next Auth Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
    <div className="min-h-screen my-2">
      <div className="flex justify-between">
        <div className="w-[20%]">
          <Sidebar />
        </div>
        <div className="w-[80%] rounded-xl ml-2">{children}</div>
      </div>
    </div>
  );
}
